# Generated by Django 6.0.7 on 2026-08-02 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_billing_truth_and_webhook_receipts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("sitemap_url", models.URLField(max_length=2048)),
                ("normalized_sitemap_url", models.URLField(max_length=2048)),
                ("normalized_host", models.CharField(max_length=253, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("suspension_reason", models.CharField(blank=True, default="", max_length=255)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_uuid", models.UUIDField(blank=True, null=True)),
                ("current_sync_uuid", models.UUIDField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("current_sync_started_at", models.DateTimeField(blank=True, null=True)),
                ("article_count", models.PositiveIntegerField(default=0)),
                ("active_article_count", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStateTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_state",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")], max_length=20
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")], max_length=20
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_state_changes",
                        to="core.profile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_transitions",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner", "state"], name="core_proj_owner_state_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["state", "last_sync_at"], name="core_proj_sync_idx"),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(fields=("uuid",), name="core_project_uuid_unique"),
        ),
    ]
