# Generated by Django 6.0.7 on 2026-08-02 01:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_projectstatetransition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSyncRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('initial', 'Initial')], default='initial', max_length=20)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('sitemap_kind', models.CharField(max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_requests', to='core.project')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['state', 'created_at'], name='core_sync_state_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'kind'), name='core_project_one_sync_kind'), models.UniqueConstraint(fields=('uuid',), name='core_project_sync_uuid_unique')],
            },
        ),
    ]
