# Generated by Django 6.0.7 on 2026-08-02 02:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_projectsyncrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitemapInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("sitemap_count", models.PositiveIntegerField(default=0)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="core.project",
                    ),
                ),
                (
                    "sync_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sitemap_inventory",
                        to="core.projectsyncrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SitemapCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=2048)),
                ("normalized_url", models.URLField(max_length=2048)),
                ("lastmod_hint", models.CharField(blank=True, default="", max_length=40)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="core.sitemapinventory",
                    ),
                ),
            ],
            options={
                "ordering": ["normalized_url", "id"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="active_sitemap_inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_projects",
                to="core.sitemapinventory",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitemapinventory",
            constraint=models.UniqueConstraint(
                fields=("uuid",), name="core_sitemap_inventory_uuid_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="sitemapcandidate",
            index=models.Index(
                fields=["inventory", "normalized_url"], name="core_sitemap_candidate_url_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sitemapcandidate",
            constraint=models.UniqueConstraint(
                fields=("inventory", "normalized_url"), name="core_sitemap_candidate_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sitemapcandidate",
            constraint=models.UniqueConstraint(
                fields=("uuid",), name="core_sitemap_candidate_uuid_unique"
            ),
        ),
    ]
