# Generated by Django 6.0.7 on 2026-08-02 02:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


def populate_sync_idempotency_keys(apps, schema_editor):
    sync_model = apps.get_model("core", "ProjectSyncRequest")
    for sync_request in sync_model.objects.filter(idempotency_key__isnull=True).iterator():
        sync_request.idempotency_key = f"legacy:{sync_request.uuid}"
        sync_request.save(update_fields=["idempotency_key"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_sitemapinventory_sitemapcandidate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageCrawlWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("broker_task_id", models.CharField(blank=True, default="", max_length=64)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="projectsyncrequest",
            name="core_project_one_sync_kind",
        ),
        migrations.AddField(
            model_name="projectsyncrequest",
            name="broker_task_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="projectsyncrequest",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectsyncrequest",
            name="failed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectsyncrequest",
            name="idempotency_key",
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=160, null=True),
        ),
        migrations.RunPython(populate_sync_idempotency_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="projectsyncrequest",
            name="idempotency_key",
            field=models.CharField(default=uuid.uuid4, max_length=160, unique=True),
        ),
        migrations.AddField(
            model_name="projectsyncrequest",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="projectsyncrequest",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectsyncrequest",
            name="queued_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectsyncrequest",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectsyncrequest",
            name="succeeded_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectsyncrequest",
            name="total_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="projectsyncrequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("initial", "Initial"),
                    ("daily", "Daily"),
                    ("manual", "Manual"),
                    ("repair", "Repair"),
                ],
                default="initial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectsyncrequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("partial", "Partial"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="projectsyncrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["queued", "running"])),
                fields=("project",),
                name="core_project_one_active_sync",
            ),
        ),
        migrations.AddField(
            model_name="pagecrawlwork",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crawl_work",
                to="core.sitemapcandidate",
            ),
        ),
        migrations.AddField(
            model_name="pagecrawlwork",
            name="sync_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_work",
                to="core.projectsyncrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="pagecrawlwork",
            index=models.Index(
                fields=["state", "next_attempt_at"], name="core_page_work_retry_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagecrawlwork",
            index=models.Index(
                fields=["sync_request", "state"], name="core_page_work_sync_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecrawlwork",
            constraint=models.UniqueConstraint(
                fields=("sync_request", "candidate"), name="core_page_work_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecrawlwork",
            constraint=models.UniqueConstraint(fields=("uuid",), name="core_page_work_uuid_unique"),
        ),
    ]
