# Generated by Django 6.0.7 on 2026-08-02 02:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pagecrawlwork_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('empty', 'Empty'), ('noindex', 'Noindex')], max_length=20)),
                ('final_url', models.URLField(max_length=2048)),
                ('canonical_url', models.URLField(max_length=2048)),
                ('http_status', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('language', models.CharField(blank=True, default='', max_length=35)),
                ('text', models.TextField(blank=True, default='')),
                ('noindex', models.BooleanField(default=False)),
                ('source_bytes', models.PositiveIntegerField(default=0)),
                ('text_chars', models.PositiveIntegerField(default=0)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='core.pagecrawlwork')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('uuid',), name='core_page_extraction_uuid_unique')],
            },
        ),
    ]
