# Generated by Django 6.0.7 on 2026-08-02 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pageextractionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageextractionresult',
            name='outbound_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(max_length=2048)),
                ('final_url', models.URLField(max_length=2048)),
                ('canonical_url', models.URLField(max_length=2048)),
                ('normalized_canonical_url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('language', models.CharField(blank=True, default='', max_length=35)),
                ('content', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extraction_state', models.CharField(choices=[('ready', 'Ready'), ('empty', 'Empty'), ('noindex', 'Noindex')], max_length=20)),
                ('state', models.CharField(choices=[('discovered', 'Discovered'), ('active', 'Active'), ('inactive', 'Inactive')], default='discovered', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('inactivity_reason', models.CharField(blank=True, default='', max_length=64)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_fetched_at', models.DateTimeField()),
                ('last_changed_at', models.DateTimeField()),
                ('inactive_at', models.DateTimeField(blank=True, null=True)),
                ('qdrant_point_id', models.UUIDField(editable=False, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.project')),
            ],
            options={
                'ordering': ['normalized_canonical_url', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCrawlAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
                ('requested_url', models.URLField(max_length=2048)),
                ('final_url', models.URLField(blank=True, default='', max_length=2048)),
                ('canonical_url', models.URLField(blank=True, default='', max_length=2048)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extraction_state', models.CharField(blank=True, default='', max_length=20)),
                ('source_bytes', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('fetched_at', models.DateTimeField()),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_attempts', to='core.article')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_attempts', to='core.project')),
                ('sync_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_attempts', to='core.projectsyncrequest')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_attempts', to='core.pagecrawlwork')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSourceURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_url', models.URLField(max_length=2048)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('inactive_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_urls', to='core.article')),
                ('last_seen_sync', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_article_sources', to='core.projectsyncrequest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_sources', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundLinkObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_destination_url', models.URLField(max_length=2048)),
                ('anchor_text', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('inactive_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_sync', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observed_outbound_links', to='core.projectsyncrequest')),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_links', to='core.article')),
                ('target_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_links', to='core.article')),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['project', 'state'], name='core_article_project_state_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['normalized_canonical_url'], name='core_article_canonical_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('uuid',), name='core_article_uuid_unique'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('project', 'normalized_canonical_url'), name='core_article_project_canonical_unique'),
        ),
        migrations.AddIndex(
            model_name='articlecrawlattempt',
            index=models.Index(fields=['project', 'fetched_at'], name='core_article_attempt_project_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlecrawlattempt',
            constraint=models.UniqueConstraint(fields=('uuid',), name='core_article_attempt_uuid_unique'),
        ),
        migrations.AddConstraint(
            model_name='articlecrawlattempt',
            constraint=models.UniqueConstraint(fields=('work', 'attempt_number'), name='core_article_attempt_work_number_unique'),
        ),
        migrations.AddIndex(
            model_name='articlesourceurl',
            index=models.Index(fields=['project', 'is_active'], name='core_article_source_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlesourceurl',
            constraint=models.UniqueConstraint(fields=('uuid',), name='core_article_source_uuid_unique'),
        ),
        migrations.AddConstraint(
            model_name='articlesourceurl',
            constraint=models.UniqueConstraint(fields=('project', 'normalized_url'), name='core_article_source_project_url_unique'),
        ),
        migrations.AddIndex(
            model_name='outboundlinkobservation',
            index=models.Index(fields=['target_article', 'is_active'], name='core_outbound_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='outboundlinkobservation',
            constraint=models.UniqueConstraint(fields=('uuid',), name='core_outbound_link_uuid_unique'),
        ),
        migrations.AddConstraint(
            model_name='outboundlinkobservation',
            constraint=models.UniqueConstraint(fields=('source_article', 'normalized_destination_url'), name='core_outbound_link_source_url_unique'),
        ),
    ]
