# Generated by Django 6.0.7 on 2026-08-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pageextractionresult_outbound_links_article_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articlecrawlattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'succeeded')), fields=('work',), name='core_article_attempt_one_success'),
        ),
    ]
