# Generated by Django 6.0.7 on 2026-08-02 04:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_articlecrawlattempt_core_article_attempt_one_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
                ('vector', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=255)),
                ('dimensions', models.PositiveIntegerField()),
                ('input_chars', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='core.article')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('uuid',), name='core_article_embedding_uuid_unique')],
            },
        ),
    ]
