# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_articleembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesourceurl",
            name="consecutive_missing_syncs",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
