# Generated by Django 6.0.7 on 2026-08-02

import uuid
from urllib.parse import urlsplit

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def backfill_detected_links(apps, schema_editor):
    Article = apps.get_model("core", "Article")
    DetectedNetworkLink = apps.get_model("core", "DetectedNetworkLink")
    OutboundLinkObservation = apps.get_model("core", "OutboundLinkObservation")
    Project = apps.get_model("core", "Project")
    detected = []
    now = timezone.now()
    observations = OutboundLinkObservation.objects.select_related(
        "source_article__project"
    ).iterator()
    for observation in observations:
        parsed = urlsplit(observation.normalized_destination_url)
        try:
            host = parsed.hostname.rstrip(".").encode("idna").decode("ascii").lower()
        except (AttributeError, UnicodeError):
            continue
        target_project = Project.objects.filter(normalized_host=host).first()
        if target_project is None:
            continue
        targets = list(
            Article.objects.filter(
                Q(normalized_canonical_url=observation.normalized_destination_url)
                | Q(source_urls__normalized_url=observation.normalized_destination_url),
                project=target_project,
            )
            .select_related("project")
            .distinct()
            .order_by("id")[:2]
        )
        target = targets[0] if len(targets) == 1 else None
        active = bool(
            observation.is_active
            and observation.source_article.is_active
            and observation.source_article.project.state == "active"
            and target_project.state == "active"
            and (target is None or target.is_active)
        )
        detected.append(
            DetectedNetworkLink(
                observation=observation,
                source_article=observation.source_article,
                target_project=target_project,
                target_article=target,
                normalized_destination_url=observation.normalized_destination_url,
                anchor_text=observation.anchor_text,
                first_detected_at=observation.first_seen_at,
                last_detected_at=observation.last_seen_at,
                is_active=active,
                inactive_at=None if active else now,
            )
        )
    DetectedNetworkLink.objects.bulk_create(detected, batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_articlesourceurl_consecutive_missing_syncs"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectedNetworkLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("normalized_destination_url", models.URLField(max_length=2048)),
                ("anchor_text", models.CharField(blank=True, default="", max_length=300)),
                ("first_detected_at", models.DateTimeField()),
                ("last_detected_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("inactive_at", models.DateTimeField(blank=True, null=True)),
                (
                    "observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_network_link",
                        to="core.outboundlinkobservation",
                    ),
                ),
                (
                    "source_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_links_given",
                        to="core.article",
                    ),
                ),
                (
                    "target_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_links_received",
                        to="core.project",
                    ),
                ),
                (
                    "target_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detected_links_received",
                        to="core.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "detected network link",
                "indexes": [
                    models.Index(
                        fields=["source_article", "is_active"],
                        name="core_detected_source_idx",
                    ),
                    models.Index(
                        fields=["target_project", "is_active"],
                        name="core_detected_project_idx",
                    ),
                    models.Index(
                        fields=["target_article", "is_active"],
                        name="core_detected_target_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("uuid",), name="core_detected_link_uuid_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("source_article", "normalized_destination_url"),
                        name="core_detected_link_source_url_unique",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_detected_links, migrations.RunPython.noop),
    ]
