# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_detectednetworklink"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="projectsyncrequest",
            index=models.Index(
                fields=["project", "-created_at"],
                name="core_sync_project_latest_idx",
            ),
        ),
    ]
