# Generated by Django 6.0.7 on 2026-08-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_projectsync_latest_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
    ]
