# Generated by Django 6.0.7 on 2026-08-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_profile_api_key_ciphertext"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ahrefs_domain_rating",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="ahrefs_domain_rating_updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ahrefs_domain_rating__isnull", True),
                    models.Q(("ahrefs_domain_rating__gte", 0), ("ahrefs_domain_rating__lte", 100)),
                    _connector="OR",
                ),
                name="core_project_ahrefs_dr_range",
            ),
        ),
    ]
