# Generated by Django 6.0.8 on 2026-09-19 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project_ahrefs_domain_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDeletionCleanup',
            fields=[
                ('project_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
