# Generated by Django 6.0.8 on 2026-09-29 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_projectdeletioncleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('domain_rating_updated_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_pages', models.PositiveIntegerField()),
                ('links_out', models.PositiveIntegerField()),
                ('domains_out', models.PositiveIntegerField()),
                ('links_in', models.PositiveIntegerField()),
                ('domains_in', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='core.project')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('project', 'date'), name='core_metric_project_day_unique')],
            },
        ),
    ]
