"""
Django settings for citeguild project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import logging
import os
from pathlib import Path
from urllib.parse import quote

import environ
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.redis import RedisIntegration

from citeguild.sentry_utils import (
    CustomLoggingIntegration,
    before_send,
    before_send_log,
    build_traces_sampler,
    logging_level_from_env,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(BASE_DIR / ".env")

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Options: dev, prod
ENVIRONMENT = env("ENVIRONMENT")
APP_PROCESS_TYPE = env("APP_PROCESS_TYPE", default="server")
DEFAULT_SERVICE_NAME = "citeguild-worker" if APP_PROCESS_TYPE == "worker" else "citeguild-web"
SERVICE_NAME = env("SERVICE_NAME", default=DEFAULT_SERVICE_NAME)
SERVICE_VERSION = env("SERVICE_VERSION", default="")

SENTRY_DSN = env("SENTRY_DSN", default="")
SENTRY_ENABLED = env.bool("SENTRY_ENABLED", default=bool(SENTRY_DSN) and ENVIRONMENT == "prod")
SENTRY_ACTIVE = SENTRY_ENABLED and bool(SENTRY_DSN)
SENTRY_RELEASE = env("SENTRY_RELEASE", default=SERVICE_VERSION)
SENTRY_TRACES_SAMPLE_RATE = env.float("SENTRY_TRACES_SAMPLE_RATE", default=1.0)
SENTRY_BACKGROUND_TRACES_SAMPLE_RATE = env.float(
    "SENTRY_BACKGROUND_TRACES_SAMPLE_RATE",
    default=0.1,
)
SENTRY_PROFILE_SESSION_SAMPLE_RATE = env.float(
    "SENTRY_PROFILE_SESSION_SAMPLE_RATE",
    default=1.0,
)
SENTRY_ENABLE_LOGS = env.bool("SENTRY_ENABLE_LOGS", default=True)
SENTRY_BREADCRUMB_LEVEL = logging_level_from_env(
    env("SENTRY_BREADCRUMB_LEVEL", default="INFO"),
    logging.INFO,
)
SENTRY_EVENT_LEVEL = logging_level_from_env(
    env("SENTRY_EVENT_LEVEL", default="ERROR"),
    logging.ERROR,
)
SENTRY_LOGS_LEVEL = logging_level_from_env(
    env("SENTRY_LOGS_LEVEL", default="WARNING"),
    logging.WARNING,
)
SENTRY_SEND_DEFAULT_PII = env.bool("SENTRY_SEND_DEFAULT_PII", default=False)
SENTRY_INCLUDE_LOCAL_VARIABLES = env.bool("SENTRY_INCLUDE_LOCAL_VARIABLES", default=False)
SENTRY_MAX_BREADCRUMBS = env.int("SENTRY_MAX_BREADCRUMBS", default=100)
SENTRY_DJANGO_MIDDLEWARE_SPANS = env.bool("SENTRY_DJANGO_MIDDLEWARE_SPANS", default=True)
SENTRY_DJANGO_CACHE_SPANS = env.bool("SENTRY_DJANGO_CACHE_SPANS", default=True)

POSTHOG_API_KEY = env("POSTHOG_API_KEY", default="")
POSTHOG_HOST = env("POSTHOG_HOST", default="https://us.i.posthog.com").rstrip("/")
POSTHOG_BROWSER_HOST = env("POSTHOG_BROWSER_HOST", default="").strip() or POSTHOG_HOST
POSTHOG_LOGS_ENDPOINT = f"{POSTHOG_HOST}/i/v1/logs"
POSTHOG_LOGS_ENABLED = env.bool(
    "POSTHOG_LOGS_ENABLED",
    default=ENVIRONMENT == "prod" and bool(POSTHOG_API_KEY),
)
POSTHOG_LOGS_ACTIVE = POSTHOG_LOGS_ENABLED and bool(POSTHOG_API_KEY)
POSTHOG_LOG_LEVEL = env("POSTHOG_LOG_LEVEL", default="INFO").upper()
if POSTHOG_LOG_LEVEL not in logging.getLevelNamesMapping():
    POSTHOG_LOG_LEVEL = "INFO"
POSTHOG_AI_OBSERVABILITY_ENABLED = env.bool(
    "POSTHOG_AI_OBSERVABILITY_ENABLED",
    default=False,
)
POSTHOG_SERVICE_NAME = env("POSTHOG_SERVICE_NAME", default="citeguild")
POSTHOG_SERVICE_VERSION = (
    env("SENTRY_RELEASE", default="") or env("GITHUB_SHA", default="") or "unknown"
)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

SITE_URL = env("SITE_URL")
SITE_HOST = SITE_URL.replace("http://", "").replace("https://", "").split("/")[0].split(":")[0]
BLOG_POSTS_DIR = BASE_DIR / "apps" / "pages" / "posts"


# HTTPS defaults used for secure production redirects, cookies, and HSTS.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if ENVIRONMENT == "prod" else None
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=ENVIRONMENT == "prod")
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=ENVIRONMENT == "prod")
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=ENVIRONMENT == "prod")
SECURE_HSTS_SECONDS = env.int(
    "SECURE_HSTS_SECONDS",
    default=31536000 if ENVIRONMENT == "prod" else 0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)

# Keep production locked to the configured site hostname.
ALLOWED_HOSTS = [SITE_HOST]
CSRF_TRUSTED_ORIGINS = [SITE_URL]

if DEBUG:
    # Local integration work often runs through ephemeral tunnel hostnames.
    ALLOWED_HOSTS = ["*"]
    CSRF_TRUSTED_ORIGINS = [
        SITE_URL,
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://backend:8000",
        "https://*.ngrok-free.app",
        "https://*.ngrok.app",
        "https://*.trycloudflare.com",
        "https://*.loca.lt",
    ]

DEFAULT_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django.contrib.humanize",
]

THIRD_PARTY_APPS = [
    "widget_tweaks",
    "anymail",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.mfa",
    "django_q",
    "django_extensions",
    "mjml",
]

CUSTOM_APPS = [
    "apps.core.CoreConfig",
    "apps.api.ApiConfig",
    "apps.mcp_server.apps.McpServerConfig",
    "apps.pages.PagesConfig",
]

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + CUSTOM_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "citeguild.logging_utils.RequestLogContextMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "citeguild.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR.joinpath("frontend", "templates"))],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.current_state",
                "apps.core.context_processors.mfa_recovery_codes_settings",
                "apps.core.context_processors.public_site_url",
                "apps.core.context_processors.posthog_api_key",
                "apps.core.context_processors.chatwoot_config",
                "apps.core.context_processors.mjml_url",
                "apps.core.context_processors.available_social_providers",
                "apps.pages.context_processors.referrer_banner",
            ],
        },
    },
]

WSGI_APPLICATION = "citeguild.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = env("DATABASE_URL", default="")

if DATABASE_URL:
    DATABASES = {
        "default": env.db("DATABASE_URL"),
    }
else:
    POSTGRES_DB = env("POSTGRES_DB")
    POSTGRES_USER = env("POSTGRES_USER")
    POSTGRES_PASSWORD = env("POSTGRES_PASSWORD")
    POSTGRES_HOST = env("POSTGRES_HOST")
    POSTGRES_PORT = env("POSTGRES_PORT", default="5432")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": POSTGRES_DB,
            "USER": POSTGRES_USER,
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": POSTGRES_HOST,
            "PORT": POSTGRES_PORT,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR.joinpath("static/")

STATICFILES_DIRS = [
    BASE_DIR.joinpath("frontend/static"),
]

folder_name = f"citeguild-{ENVIRONMENT}"
aws_s3_endpoint_url = env("AWS_S3_ENDPOINT_URL", default="")

MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

if not aws_s3_endpoint_url:
    MEDIA_URL = "/media/"
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": MEDIA_ROOT,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    MEDIA_URL = f"{aws_s3_endpoint_url}/{folder_name}/"
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": folder_name,
                "default_acl": "public-read",
                "region_name": "eu-east-1",
                "endpoint_url": aws_s3_endpoint_url,
                "access_key": env("AWS_ACCESS_KEY_ID"),
                "secret_key": env("AWS_SECRET_ACCESS_KEY"),
                "querystring_auth": False,
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
SITE_ID = 1

EMAIL_BACKEND_OVERRIDE = env("EMAIL_BACKEND", default="")
EMAIL_HOST = env("EMAIL_HOST", default="mailhog" if DEBUG else "")
EMAIL_PORT = env.int("EMAIL_PORT", default=1025)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")

LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT_URL = "landing"

ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*"]
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""
ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS = False
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = True
ACCOUNT_CHANGE_EMAIL = True
ALLOW_SIGNUPS = env.bool("ALLOW_SIGNUPS", default=True)
ACCOUNT_FORMS = {
    "signup": "apps.core.forms.CustomSignUpForm",
    "login": "apps.core.forms.CustomLoginForm",
}
ACCOUNT_ADAPTER = "citeguild.adapters.CustomAccountAdapter"
if ENVIRONMENT != "dev":
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

# Passkey (WebAuthn) auth support via django-allauth MFA.
MFA_SUPPORTED_TYPES = ["webauthn", "recovery_codes"]
MFA_PASSKEY_LOGIN_ENABLED = True
MFA_PASSKEY_SIGNUP_ENABLED = True
# Local dev uses http://localhost, so allow insecure origin only in debug.
MFA_WEBAUTHN_ALLOW_INSECURE_ORIGIN = DEBUG

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_PROVIDERS = {}
SOCIALACCOUNT_ADAPTER = "citeguild.adapters.CustomSocialAccountAdapter"

GITHUB_CLIENT_ID = env("GITHUB_CLIENT_ID", default="")
if GITHUB_CLIENT_ID != "":
    SOCIALACCOUNT_PROVIDERS["github"] = {
        "VERIFIED_EMAIL": True,
        "EMAIL_AUTHENTICATION": True,
        "AUTO_SIGNUP": True,
        "APP": {
            "client_id": env("GITHUB_CLIENT_ID"),
            "secret": env("GITHUB_CLIENT_SECRET"),
        },
    }

MAILGUN_API_KEY = env("MAILGUN_API_KEY", default="")
ANYMAIL = {
    "MAILGUN_API_KEY": MAILGUN_API_KEY,
    "MAILGUN_SENDER_DOMAIN": env(
        "MAILGUN_SENDER_DOMAIN",
        default="mg.citeguild.app",
    ),
}
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default=("LVTD LLC from CiteGuild <hello@citeguild.app>"),
)
SERVER_EMAIL = env(
    "SERVER_EMAIL",
    default=("CiteGuild Errors <error@citeguild.app>"),
)

if EMAIL_BACKEND_OVERRIDE:
    EMAIL_BACKEND = EMAIL_BACKEND_OVERRIDE
elif DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
elif MAILGUN_API_KEY == "":
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"

EMAIL_DELIVERY_RETRY_BACKOFF_SECONDS = (0.0, 1.0, 3.0)


HEALTHCHECKS_PING_BASE_URL = env("HEALTHCHECKS_PING_BASE_URL", default="")
REDIS_HOST = env("REDIS_HOST", default="localhost")
REDIS_PORT = env("REDIS_PORT", default="6379")
REDIS_PASSWORD = env("REDIS_PASSWORD", default="")
REDIS_DB = env("REDIS_DB", default="0")


def build_redis_url(host: str, port: str, db: str, password: str = "") -> str:
    encoded_password = quote(password, safe="")
    credentials = f":{encoded_password}@" if password else ""
    return f"redis://{credentials}{host}:{port}/{db}"


REDIS_URL = env("REDIS_URL", default="") or build_redis_url(
    host=REDIS_HOST,
    port=REDIS_PORT,
    db=REDIS_DB,
    password=REDIS_PASSWORD,
)
LOCAL_INSTANCE_ID = env("LOCAL_INSTANCE_ID", default="citeguild")
CACHE_KEY_PREFIX = env("CACHE_KEY_PREFIX", default=LOCAL_INSTANCE_ID)
Q_CLUSTER_NAME = env("Q_CLUSTER_NAME", default=f"{LOCAL_INSTANCE_ID}-q")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "KEY_PREFIX": CACHE_KEY_PREFIX,
    }
}

Q_CLUSTER = {
    "name": Q_CLUSTER_NAME,
    "timeout": 3600,  # 1 hour
    "retry": 4800,  # 80 minutes
    "workers": 4,
    "max_attempts": 2,
    "redis": REDIS_URL,
    "ALT_CLUSTERS": {},
    "error_reporter": {},
}

USE_EXISTING_TEST_DATABASE = env.bool("DJANGO_TEST_USE_EXISTING_DATABASE", default=False)

if USE_EXISTING_TEST_DATABASE:
    CACHES["default"] = {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "citeguild-pgsandbox-tests",
    }
    Q_CLUSTER.pop("redis", None)
    Q_CLUSTER["orm"] = "default"

LOG_LEVEL = env("DJANGO_LOG_LEVEL", default="INFO").upper()
if LOG_LEVEL not in logging.getLevelNamesMapping():
    LOG_LEVEL = "INFO"

DJANGO_LOG_FORMAT = env(
    "DJANGO_LOG_FORMAT",
    default="json" if ENVIRONMENT == "prod" else "console",
).lower()
LOGGING_HANDLER_NAME = "json_console" if DJANGO_LOG_FORMAT == "json" else "console"
LOGGING_HANDLERS = [LOGGING_HANDLER_NAME]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "root": {
        "handlers": list(LOGGING_HANDLERS),
        "level": LOG_LEVEL,
    },
    "formatters": {
        "console": {
            "()": "citeguild.logging_utils.ConsoleFormatter",
        },
        "json": {
            "()": "citeguild.logging_utils.JsonFormatter",
            "service_name": SERVICE_NAME,
            "service_namespace": "citeguild",
            "service_version": SERVICE_VERSION,
            "environment": ENVIRONMENT,
        },
    },
    "filters": {
        "request_context": {
            "()": "citeguild.logging_utils.RequestContextFilter",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "filters": ["request_context"],
            "class": "logging.StreamHandler",
            "formatter": "console",
            "level": "DEBUG",
        },
        "json_console": {
            "filters": ["request_context"],
            "class": "logging.StreamHandler",
            "formatter": "json",
            "level": "DEBUG",
        },
    },
    "loggers": {
        "django": {
            "handlers": list(LOGGING_HANDLERS),
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": list(LOGGING_HANDLERS),
            "level": "WARNING" if ENVIRONMENT == "prod" else "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": list(LOGGING_HANDLERS),
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": list(LOGGING_HANDLERS),
            "level": "WARNING",
            "propagate": False,
        },
        "citeguild": {
            "handlers": list(LOGGING_HANDLERS),
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "apps": {
            "handlers": list(LOGGING_HANDLERS),
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

if POSTHOG_LOGS_ACTIVE:
    LOGGING["handlers"]["posthog"] = {
        "()": "citeguild.posthog_logging.PostHogLoggingHandler",
        "filters": ["request_context"],
        "level": POSTHOG_LOG_LEVEL,
        "endpoint": POSTHOG_LOGS_ENDPOINT,
        "api_key": POSTHOG_API_KEY,
        "service_name": SERVICE_NAME,
        "service_namespace": "citeguild",
        "service_version": SERVICE_VERSION,
        "environment": ENVIRONMENT,
    }
    for application_logger in ("apps", "citeguild"):
        LOGGING["loggers"][application_logger]["handlers"].append("posthog")

if SENTRY_ACTIVE:
    Q_CLUSTER["error_reporter"]["sentry"] = {"dsn": SENTRY_DSN}
    sentry_sdk.init(
        debug=DEBUG,
        dsn=SENTRY_DSN,
        environment=ENVIRONMENT,
        release=SENTRY_RELEASE or None,
        send_default_pii=SENTRY_SEND_DEFAULT_PII,
        traces_sampler=build_traces_sampler(
            http_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
            background_sample_rate=SENTRY_BACKGROUND_TRACES_SAMPLE_RATE,
        ),
        profile_session_sample_rate=SENTRY_PROFILE_SESSION_SAMPLE_RATE,
        profile_lifecycle="trace",
        enable_logs=SENTRY_ENABLE_LOGS,
        max_breadcrumbs=SENTRY_MAX_BREADCRUMBS,
        integrations=[
            DjangoIntegration(
                middleware_spans=SENTRY_DJANGO_MIDDLEWARE_SPANS,
                cache_spans=SENTRY_DJANGO_CACHE_SPANS,
            ),
            RedisIntegration(),
            CustomLoggingIntegration(
                level=SENTRY_BREADCRUMB_LEVEL,
                event_level=SENTRY_EVENT_LEVEL,
                sentry_logs_level=SENTRY_LOGS_LEVEL,
            ),
        ],
        before_send=before_send,
        before_send_log=before_send_log,
        attach_stacktrace=True,
        include_local_variables=SENTRY_INCLUDE_LOCAL_VARIABLES,
    )

CHATWOOT_BASE_URL = env("CHATWOOT_BASE_URL", default="")
CHATWOOT_WEBSITE_TOKEN = env("CHATWOOT_WEBSITE_TOKEN", default="")
CHATWOOT_HMAC_SECRET = env("CHATWOOT_HMAC_SECRET", default="")

ADMIN_NOTIFICATION_EMAIL_RECIPIENTS = env.list(
    "ADMIN_NOTIFICATION_EMAIL_RECIPIENTS",
    default=["LVTD LLC <rasul@lvtd.dev>"],
)
ADMIN_NOTIFICATION_EMAIL_FALLBACK = env.bool("ADMIN_NOTIFICATION_EMAIL_FALLBACK", default=True)
APPRISE_API_URL = env("APPRISE_API_URL", default="")
APPRISE_CONFIG_KEY = env("APPRISE_CONFIG_KEY", default="")
APPRISE_BASIC_AUTH_USER = env("APPRISE_BASIC_AUTH_USER", default="")
APPRISE_BASIC_AUTH_PASSWORD = env("APPRISE_BASIC_AUTH_PASSWORD", default="")
APPRISE_NOTIFICATION_FORMAT = env("APPRISE_NOTIFICATION_FORMAT", default="markdown")
APPRISE_REQUEST_TIMEOUT = env.int("APPRISE_REQUEST_TIMEOUT", default=10)

STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default="")
STRIPE_LIVE_MODE = ENVIRONMENT == "prod"
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_WEBHOOK_UUID = env("WEBHOOK_UUID", default="")
STRIPE_PRICE_ID_MONTHLY = env("STRIPE_PRICE_ID_MONTHLY", default="")
STRIPE_PRICE_ID_YEARLY = env("STRIPE_PRICE_ID_YEARLY", default="")
STRIPE_PRICE_IDS = {
    "monthly": STRIPE_PRICE_ID_MONTHLY,
    "yearly": STRIPE_PRICE_ID_YEARLY,
}

MJML_BACKEND_MODE = "httpserver"
MJML_URL = env("MJML_URL", default="")
MJML_HTTPSERVERS = [
    {
        "URL": f"{MJML_URL}/v1/render",
    }
]
SHELL_PLUS_IMPORTS = [
    "from django_q.tasks import async_task",
    "from apps.core.tasks import *",
]

OPENROUTER_API_KEY = env("OPENROUTER_API_KEY", default="")
AI_MODELS = {
    "fast": env("OPENROUTER_MODEL_FAST", default="openai/gpt-5-nano"),
    "smart": env("OPENROUTER_MODEL_SMART", default="anthropic/claude-sonnet-4.5"),
}

QDRANT_URL = env("QDRANT_URL", default="").strip()
QDRANT_API_KEY = env("QDRANT_API_KEY", default="")
QDRANT_TIMEOUT_SECONDS = env.float("QDRANT_TIMEOUT_SECONDS", default=5.0)
